version: "3"
services:
  node:
    build: 
      context: ./node
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_PREFIX=/home/node/app/.npm-global
    volumes:
      - ./data:/home/node/app
    tty: true
    ports:
      - "20000-20100:20000-20100"