version: "3"
services:
  php: 
    build:
      context: ./data/php
    image: php:7.2-fpm
    working_dir: /var/www/html
    ports:
      - 28000:8000
    volumes:
      - ./data/php/html:/var/www/html
    depends_on:
      - db
  node:
    build: 
      context: ./node
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_PREFIX=/home/node/app/.npm-global
    volumes:
      - ./data/php/html:/home/node/app
    tty: true
    ports:
      - "28001:8000"
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./data/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  nginx:
    image: nginx:alpine
    ports:
      - 38888:80
  db_test_client:
    image: mysql:5.7
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret